### ISSUE TITLE
Import doesn't import file

### ISSUE THREAD

**Issue by Shampra** [anyproto/anytype-heart#456]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When we export a page (as JSON whith file and linked object) and import it again, import doesn't download files.

Before export : 
![image](https://github.com/anyproto/anytype-heart/assets/16141040/a968e213-c841-4302-9306-c761a3fceed3)

After import exported JSON : 
![image](https://github.com/anyproto/anytype-heart/assets/16141040/adb07f16-05c3-4253-9096-383f1030b507)

### Expected Behavior

Files must be downloaded

### Steps To Reproduce

1. Create a page
2. Add files (pdf, image, video, ...)
3. Export page as JSON with files and linked objects
4. Check exported file : a files folder is present with your files ([and more...](https://community.anytype.io/t/at-seems-to-never-delete-nor-unlink-png-file-and-hide-this-fact-and-export-them/11345) 😅)
5. Clean AT (delete page and files, included in bin)
6. Import your json
7. Check your page : no more files

### Environment

```markdown
- OS:Windows 10
- Version: Desktop 0.35.2
```

**Comment by Shampra** [comment]
Any ETA?
I'm closely following the topic to finish the conversion tool as soon as possible.
Thanks :)

**Comment by fuksman** [comment]
@Shampra, it should be delivered with the latest release, along with other fixes for the JSON import/export issues you reported. Please check 🙏

**Comment by Shampra** [comment]
it seems to work... damn, I'll have to work on the converter again 😅.  
Thanks!

**Comment by Shampra** [comment]
Oh, pehaps it explains this issue : [https://community.anytype.io/t/imported-file-not-visible-with-set/12308](https://community.anytype.io/t/imported-file-not-visible-with-set/12308)  
Object is not really imported.

**Comment by Shampra** [comment]
Always with v0.36.14-alpha

Any ETA please?  
 

![](https://github.com/anyproto/anytype-heart/assets/16141040/7ccdbadd-c404-4cb1-9bae-ac7f5752fd34)

**Comment by hskrtich** [comment]
@fuksman Have you have a chance to take a look at this?

**Comment by Shampra** [comment]
Yest, tested yesterday with 0.37.6-alpha.  
  
\- Create a page with file  
\- Go offline  
\- Export page  
\- change account/space  
\- Import page  
Failed (the only change is that now the file size is indicated)

![](https://github.com/anyproto/anytype-heart/assets/16141040/5e05ae9b-315a-4624-be6b-340c30bde5d9)

  
 

https://community.anytype.io/t/export-why-import-need-internet-access/12517/4

**Comment by fuksman** [comment]
@hskrtich @Shampra hey there. Yes, we confirm that the problem is on our side, and we aim to fix it along with the files refactoring (files as objects, expected to be delivered in the next release).

**Comment by Shampra** [comment]
I've just tested today's version, and it's better than ever!   
Image (and sound or pdf) files are displayed on the page. However, it's impossible to open the object.  
And the same goes for other files (text, etc.).  
In both cases, clicking on them takes you back to the homepage.

If it's still open, I guess it's normal, otherwise it may be useful  😉

**Comment by Shampra** [comment]
I want to be sure that importing from another source (note from Evernote ) works, so I make sure to block any potential source of recovery internal to Anytype.

- In Anytype **0.37.17-beta** in a standard account (not local only mode), I create a space, create an object page, add some stuff (here : an image, a txt file, a mp3, a pdf as link)
![image](https://github.com/anyproto/anytype-heart/assets/16141040/71503308-1f9e-457c-9993-cdc47c2f3972)
- I cut the network (now or before)
- I export the page as JSON with all checked expect archived files
![image](https://github.com/anyproto/anytype-heart/assets/16141040/8bda617f-f880-4663-b7a2-5f37207b14b9)

- I delete the space 
- I create a new empty space 
- File -> Import -> Anyblock : OK
In the imported page : 
- the sound and the pdf works fine, I can use them inline or open them as object
- Image is fine inline but if I want to open as object : Homage; same file file, if I click on it, I arrive on the homepage
![demobugAnytype](https://github.com/anyproto/anytype-heart/assets/16141040/c598e7bc-dc3e-40da-b36c-0d705e0d6b3e)

**Comment by AnastasiaShemyakinskaya** [comment]
Do you have these files in your export archive in file folder?

**Comment by Shampra** [comment]
Yes
Here's the export (nothing sensitive, I think)
[Uploading Anytype.20240124.152633.69.zip…]()

**Comment by Shampra** [comment]
It can be closed, tested ok with 0.39.0 Desktop.
Thanks
